version: '2'
services:
  jenkins-master:
    build:  ./master
    container_name: jenkins-master
    ports:
      - 4000:8080 
      - 50000:50000
    volumes:
      - ../jenkins_data:/var/jenkins_home
    user: jenkins